### PR TITLE
rebased

### PR DESCRIPTION
**Pull request by krasi-georgiev**
fixed another conflict as I merged the last commit and it was easy to resolve the conflict.

Once this is merged do you want to implement it in Prometheus and I will start a benchmark test to check if it works as expected.

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
btw if you can ping me on irc @prometheus-dev to speed things up if you want.

**Comment by mknapphrt** [comment]
Ok, i'll merge and start testing too. https://github.com/prometheus/prometheus/pull/4230 has the changes needed from prometheus, though that build is going to fail without the changes here. Namely, it doesn't have the needed `tsdb.Config` fields that are defined here.

**Comment by krasi-georgiev** [comment]
yeah that PR need to be buildable as the benchmarking builds from the actual code in the PR

**Comment by mknapphrt** [comment]
Any idea how to make it buildable without putting all the tsdb changes in? It seems like in general they merge tsdb changes all in at once on a semi-regular basis.

**Comment by mknapphrt** [comment]
Also, I the test is breaking after merging. It seems that the time waiting for the block to persist isn't long enough. I tried increasing it and the test passes but with the given time it doesn't work. Was there a reason for the length of time given? Is it ok to extend it? @krasi-georgiev

**Comment by krasi-georgiev** [comment]
No reason for the time so can increase as needed.

for the benchmark we want to prove that these changes are fine to merge in tsdb for this we need to pull all of these in Prometheus itself. This is the best way to make sure the tsdb changes will work exactly as planned in Prometheus.

I created a branch on tsdb https://github.com/prometheus/tsdb/tree/pull/343-orig

so you can use govendor to pull this into prometheus and open a PR with it so I can run the test.

from root dir 
`govendor fetch github.com/prometheus/tsdb/...@pull/343-orig`

**Comment by krasi-georgiev** [comment]
actually maybe something like this should work
GO111MODULE=on go get github.com/prometheus/tsdb@pull/343-orig

**Comment by mknapphrt** [comment]
Where would that get put? Im assuming in the makefile but I'm not sure where.
Also, I can't seem to find the prometheus-dev channel on irc

**Comment by krasi-georgiev** [comment]
no need to put it anywhere just run this command in the root 

the exact channel name is #prometheus-dev

**Pull request merged**
